/*package com.parksmart.auth_service.entity;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

public class UserTest {

    @Test
    void testUserEntity() {

        User user = new User();

        user.setUsername("raji");
        user.setPassword("1234");
        user.setRole("USER");

        assertEquals("raji", user.getUsername());
        assertEquals("1234", user.getPassword());
        assertEquals("USER", user.getRole());
    }

    @Test
    void testUserId() {

        User user = new User();

        // id is normally generated by DB
        // we only check getter exists

        assertNull(user.getId());
    }
}*/
